### ISSUE TITLE
Unsupported type in SD_Switch_Model

### ISSUE THREAD

**Issue by Foxinprone** [stassius/StableHoudini#7]
Hi there, I was following along in the tutorial and got stopped pretty early. 
My issue came from the SD_switch_model node. the dropdown menu only displays error and has no other option, despite having multiple models available on Automatic1111, which was open at the time. The traceback goes to an unsupported type, tuple. I tried digging around through the scripts, but I'm no expert. I'm running on windows10 with Houdini 19.5.569

Traceback (most recent call last):
  File "Parameter Scripted Action", line 2, in <module>
  File "Top/SD_Switch_Model, PythonModule", line 11, in RefreshModels
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\houpythonportion\Parm.py", line 83, in set
    raise TypeError(
TypeError: Cannot set parameter value to unsupported type <class 'tuple'>

**Comment by stassius** [comment]
I found the source of the bug and pushed the fix. The bug was with handling the network error. So most likely you don't have a link between Houdini and Automatic.
Please, check if you use the --api key in the bat-file and run A1111 from this very file. Also check if Houdini is not blocked in your firewall.

**Comment by Foxinprone** [comment]
Yeah, turns out I was just been a bit silly and had been running the webui.bat, even though I edited things in the webui-user.bat
